// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGVmuH-KwB-W1sT9SVRjd1MdIDcE8JHY8',
    appId: '1:224492107906:web:e8d546ff2c44c75b129c9b',
    messagingSenderId: '224492107906',
    projectId: 'infyapp-taskss',
    authDomain: 'infyapp-taskss.firebaseapp.com',
    storageBucket: 'infyapp-taskss.firebasestorage.app',
    measurementId: 'G-2RWT2J3N70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-Fxt74_LRvJtN-AVtbazFSkoQYZ8UxI',
    appId: '1:224492107906:android:77ad8e1463cbefdc129c9b',
    messagingSenderId: '224492107906',
    projectId: 'infyapp-taskss',
    storageBucket: 'infyapp-taskss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQrvRAS6FqNK0QRkiq9v3IRpVZEGkfsIU',
    appId: '1:224492107906:ios:883513f0825ad817129c9b',
    messagingSenderId: '224492107906',
    projectId: 'infyapp-taskss',
    storageBucket: 'infyapp-taskss.firebasestorage.app',
    iosBundleId: 'com.example.infyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQrvRAS6FqNK0QRkiq9v3IRpVZEGkfsIU',
    appId: '1:224492107906:ios:883513f0825ad817129c9b',
    messagingSenderId: '224492107906',
    projectId: 'infyapp-taskss',
    storageBucket: 'infyapp-taskss.firebasestorage.app',
    iosBundleId: 'com.example.infyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGVmuH-KwB-W1sT9SVRjd1MdIDcE8JHY8',
    appId: '1:224492107906:web:31e4078ef33b2103129c9b',
    messagingSenderId: '224492107906',
    projectId: 'infyapp-taskss',
    authDomain: 'infyapp-taskss.firebaseapp.com',
    storageBucket: 'infyapp-taskss.firebasestorage.app',
    measurementId: 'G-WGWCEYMRHX',
  );

}